server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://products
          predicates:
            - Path=/products/**
        - id: stock-service
          uri: lb://stocks
          predicates:
            - Path=/stocks/**
message: Hello from API Gateway
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
